apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: rules-enrichment-daemon-dev-bc
  labels:
    app.kubernetes.io/name: rules-enrichment-daemon
    app.kubernetes.io/part-of: rules-enrichment-daemon
    app.kubernetes.io/environment: dev
spec:
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: rules-enrichment-daemon-dev-is:latest
  triggers:
    - type: ConfigChange
