apiVersion: v1
kind: Secret
metadata:
  name: daemon-postgres-dev-secret
  labels:
    app.kubernetes.io/name: daemon-postgres
    app.kubernetes.io/environment: dev
stringData:
  POSTGRESQL_USER: daemon
  POSTGRESQL_PASSWORD: daemon
  POSTGRESQL_DATABASE: rules_enrichment_daemon
type: Opaque
